### ISSUE TITLE
Text formattering

### ISSUE THREAD

**Issue by oudend** [Scoutboy06/YamlValidator#12]
Vi använder i nuläget _c++ 17_ vilket innebär att vi inte har tillgång till [**std::format**](https://en.cppreference.com/w/cpp/utility/format) som implementerades i _c++ 20_. Troligtvis är vårt projekt kompatibelt med _c++ 20_ så det kan vara gynnsamt att byta för att ha tillgång till fler metoder i std. För att kunna använda **std::format** behöver vi dock byta c++ "Language Standard" i visual studio till "Preview - Features from the Latest C++ Working Draft (/std:c++latest)".

**Comment by Scoutboy06** [comment]
På vilket sätt skulle vi ha nytta av std::format?

**Comment by oudend** [comment]
std::format kan förenkla ganska mycket och nyttja läsbarheten av schema.cpp om vi går vidare med att använda en "message" variabel för "SchemaError". Jag tänker mig att formatet skulle kunna vara något i stil med: "Type mismatch: Expected "String" but got "Boolean" at index 4".

**Comment by Scoutboy06** [comment]
Jag ser ju ingen egentlig anledning att inte byta... Skapar du en branch som länkar till denna issuen?

**Comment by oudend** [comment]
Visst!
